In [1]:
import numpy as np

In [2]:
array1 = np.array([[10, 8], [3, 5]])

In [5]:
array2 = np.linalg.inv(array1)
array2

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [7]:
array1 @ array2
#為單位矩陣

array([[1., 0.],
       [0., 1.]])

In [8]:
eigenvalue, featurevector = np.linalg.eig(array1)

In [13]:
#特徵值
eigenvalue

array([0.07692308, 0.5       ])

In [12]:
#特徵向量
featurevector

array([[-0.93632918,  0.70710678],
       [-0.35112344, -0.70710678]])

In [14]:
#SVD
S, V, D = np.linalg.svd(array1)

In [15]:
S

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [16]:
V

array([13.94721714,  1.86417116])

In [17]:
D

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])